/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type {
  GetRoadmapNodesNodeIdResourcesPathParameters,
  GetRoadmapsIdPathParameters,
  GetUsersMeRoadmapsParams,
  PatchRoadmapNodesNodeIdStatusPathParameters,
  PatchRoadmapsIdArchivePathParameters,
  PatchRoadmapsIdKeepPathParameters,
  PostJdSubmissionsJdIdRoadmapsPathParameters,
  PostRoadmapsIdRegeneratePathParameters,
  UpdateRoadmapNodeStatusCommand
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';

export type postJdSubmissionsJdIdRoadmapsResponse200 = {
  data: void
  status: 200
}
    
export type postJdSubmissionsJdIdRoadmapsResponseSuccess = (postJdSubmissionsJdIdRoadmapsResponse200) & {
  headers: Headers;
};
;

export type postJdSubmissionsJdIdRoadmapsResponse = (postJdSubmissionsJdIdRoadmapsResponseSuccess)

export const getPostJdSubmissionsJdIdRoadmapsUrl = ({ jdId }: PostJdSubmissionsJdIdRoadmapsPathParameters,) => {


  

  return `/jd-submissions/${jdId}/roadmaps`
}

export const postJdSubmissionsJdIdRoadmaps = async ({ jdId }: PostJdSubmissionsJdIdRoadmapsPathParameters, options?: RequestInit): Promise<postJdSubmissionsJdIdRoadmapsResponse> => {
  
  return customFetch<postJdSubmissionsJdIdRoadmapsResponse>(getPostJdSubmissionsJdIdRoadmapsUrl({ jdId }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type getRoadmapsIdResponse200 = {
  data: void
  status: 200
}
    
export type getRoadmapsIdResponseSuccess = (getRoadmapsIdResponse200) & {
  headers: Headers;
};
;

export type getRoadmapsIdResponse = (getRoadmapsIdResponseSuccess)

export const getGetRoadmapsIdUrl = ({ id }: GetRoadmapsIdPathParameters,) => {


  

  return `/roadmaps/${id}`
}

export const getRoadmapsId = async ({ id }: GetRoadmapsIdPathParameters, options?: RequestInit): Promise<getRoadmapsIdResponse> => {
  
  return customFetch<getRoadmapsIdResponse>(getGetRoadmapsIdUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getUsersMeRoadmapsResponse200 = {
  data: void
  status: 200
}
    
export type getUsersMeRoadmapsResponseSuccess = (getUsersMeRoadmapsResponse200) & {
  headers: Headers;
};
;

export type getUsersMeRoadmapsResponse = (getUsersMeRoadmapsResponseSuccess)

export const getGetUsersMeRoadmapsUrl = (params?: GetUsersMeRoadmapsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/me/roadmaps?${stringifiedParams}` : `/users/me/roadmaps`
}

export const getUsersMeRoadmaps = async (params?: GetUsersMeRoadmapsParams, options?: RequestInit): Promise<getUsersMeRoadmapsResponse> => {
  
  return customFetch<getUsersMeRoadmapsResponse>(getGetUsersMeRoadmapsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type patchRoadmapNodesNodeIdStatusResponse200 = {
  data: void
  status: 200
}
    
export type patchRoadmapNodesNodeIdStatusResponseSuccess = (patchRoadmapNodesNodeIdStatusResponse200) & {
  headers: Headers;
};
;

export type patchRoadmapNodesNodeIdStatusResponse = (patchRoadmapNodesNodeIdStatusResponseSuccess)

export const getPatchRoadmapNodesNodeIdStatusUrl = ({ nodeId }: PatchRoadmapNodesNodeIdStatusPathParameters,) => {


  

  return `/roadmap-nodes/${nodeId}/status`
}

export const patchRoadmapNodesNodeIdStatus = async ({ nodeId }: PatchRoadmapNodesNodeIdStatusPathParameters,
    updateRoadmapNodeStatusCommand: UpdateRoadmapNodeStatusCommand, options?: RequestInit): Promise<patchRoadmapNodesNodeIdStatusResponse> => {
  
  return customFetch<patchRoadmapNodesNodeIdStatusResponse>(getPatchRoadmapNodesNodeIdStatusUrl({ nodeId }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRoadmapNodeStatusCommand,)
  }
);}


export type patchRoadmapsIdArchiveResponse200 = {
  data: void
  status: 200
}
    
export type patchRoadmapsIdArchiveResponseSuccess = (patchRoadmapsIdArchiveResponse200) & {
  headers: Headers;
};
;

export type patchRoadmapsIdArchiveResponse = (patchRoadmapsIdArchiveResponseSuccess)

export const getPatchRoadmapsIdArchiveUrl = ({ id }: PatchRoadmapsIdArchivePathParameters,) => {


  

  return `/roadmaps/${id}/archive`
}

export const patchRoadmapsIdArchive = async ({ id }: PatchRoadmapsIdArchivePathParameters, options?: RequestInit): Promise<patchRoadmapsIdArchiveResponse> => {
  
  return customFetch<patchRoadmapsIdArchiveResponse>(getPatchRoadmapsIdArchiveUrl({ id }),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}


export type postRoadmapsIdRegenerateResponse200 = {
  data: void
  status: 200
}
    
export type postRoadmapsIdRegenerateResponseSuccess = (postRoadmapsIdRegenerateResponse200) & {
  headers: Headers;
};
;

export type postRoadmapsIdRegenerateResponse = (postRoadmapsIdRegenerateResponseSuccess)

export const getPostRoadmapsIdRegenerateUrl = ({ id }: PostRoadmapsIdRegeneratePathParameters,) => {


  

  return `/roadmaps/${id}/regenerate`
}

export const postRoadmapsIdRegenerate = async ({ id }: PostRoadmapsIdRegeneratePathParameters, options?: RequestInit): Promise<postRoadmapsIdRegenerateResponse> => {
  
  return customFetch<postRoadmapsIdRegenerateResponse>(getPostRoadmapsIdRegenerateUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type patchRoadmapsIdKeepResponse200 = {
  data: void
  status: 200
}
    
export type patchRoadmapsIdKeepResponseSuccess = (patchRoadmapsIdKeepResponse200) & {
  headers: Headers;
};
;

export type patchRoadmapsIdKeepResponse = (patchRoadmapsIdKeepResponseSuccess)

export const getPatchRoadmapsIdKeepUrl = ({ id }: PatchRoadmapsIdKeepPathParameters,) => {


  

  return `/roadmaps/${id}/keep`
}

export const patchRoadmapsIdKeep = async ({ id }: PatchRoadmapsIdKeepPathParameters, options?: RequestInit): Promise<patchRoadmapsIdKeepResponse> => {
  
  return customFetch<patchRoadmapsIdKeepResponse>(getPatchRoadmapsIdKeepUrl({ id }),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}


export type getRoadmapNodesNodeIdResourcesResponse200 = {
  data: void
  status: 200
}
    
export type getRoadmapNodesNodeIdResourcesResponseSuccess = (getRoadmapNodesNodeIdResourcesResponse200) & {
  headers: Headers;
};
;

export type getRoadmapNodesNodeIdResourcesResponse = (getRoadmapNodesNodeIdResourcesResponseSuccess)

export const getGetRoadmapNodesNodeIdResourcesUrl = ({ nodeId }: GetRoadmapNodesNodeIdResourcesPathParameters,) => {


  

  return `/roadmap-nodes/${nodeId}/resources`
}

export const getRoadmapNodesNodeIdResources = async ({ nodeId }: GetRoadmapNodesNodeIdResourcesPathParameters, options?: RequestInit): Promise<getRoadmapNodesNodeIdResourcesResponse> => {
  
  return customFetch<getRoadmapNodesNodeIdResourcesResponse>(getGetRoadmapNodesNodeIdResourcesUrl({ nodeId }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


