/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

export const getPostAssessmentPathsPathIdCvMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/assessment-paths/:pathId/cv',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetAssessmentPathsPathIdCvMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/assessment-paths/:pathId/cv',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}
export const getCvSubmissionsMock = () => [
  getPostAssessmentPathsPathIdCvMockHandler(),
  getGetAssessmentPathsPathIdCvMockHandler()
]
