/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type {
  AdminResourceReviewRequest,
  AdminResourceUpsertRequest,
  DeleteAdminResourcesIdPathParameters,
  GetAdminResourcesParams,
  GetAdminResourcesPendingReviewParams,
  PatchAdminResourcesIdReviewPathParameters,
  PostAdminResourcesIdRejectPathParameters,
  PutAdminResourcesIdPathParameters
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';

export type getAdminResourcesResponse200 = {
  data: void
  status: 200
}
    
export type getAdminResourcesResponseSuccess = (getAdminResourcesResponse200) & {
  headers: Headers;
};
;

export type getAdminResourcesResponse = (getAdminResourcesResponseSuccess)

export const getGetAdminResourcesUrl = (params?: GetAdminResourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/resources?${stringifiedParams}` : `/admin/resources`
}

export const getAdminResources = async (params?: GetAdminResourcesParams, options?: RequestInit): Promise<getAdminResourcesResponse> => {
  
  return customFetch<getAdminResourcesResponse>(getGetAdminResourcesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postAdminResourcesResponse200 = {
  data: void
  status: 200
}
    
export type postAdminResourcesResponseSuccess = (postAdminResourcesResponse200) & {
  headers: Headers;
};
;

export type postAdminResourcesResponse = (postAdminResourcesResponseSuccess)

export const getPostAdminResourcesUrl = () => {


  

  return `/admin/resources`
}

export const postAdminResources = async (adminResourceUpsertRequest: AdminResourceUpsertRequest, options?: RequestInit): Promise<postAdminResourcesResponse> => {
  
  return customFetch<postAdminResourcesResponse>(getPostAdminResourcesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminResourceUpsertRequest,)
  }
);}


export type getAdminResourcesPendingReviewResponse200 = {
  data: void
  status: 200
}
    
export type getAdminResourcesPendingReviewResponseSuccess = (getAdminResourcesPendingReviewResponse200) & {
  headers: Headers;
};
;

export type getAdminResourcesPendingReviewResponse = (getAdminResourcesPendingReviewResponseSuccess)

export const getGetAdminResourcesPendingReviewUrl = (params?: GetAdminResourcesPendingReviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/resources/pending-review?${stringifiedParams}` : `/admin/resources/pending-review`
}

export const getAdminResourcesPendingReview = async (params?: GetAdminResourcesPendingReviewParams, options?: RequestInit): Promise<getAdminResourcesPendingReviewResponse> => {
  
  return customFetch<getAdminResourcesPendingReviewResponse>(getGetAdminResourcesPendingReviewUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type putAdminResourcesIdResponse200 = {
  data: void
  status: 200
}
    
export type putAdminResourcesIdResponseSuccess = (putAdminResourcesIdResponse200) & {
  headers: Headers;
};
;

export type putAdminResourcesIdResponse = (putAdminResourcesIdResponseSuccess)

export const getPutAdminResourcesIdUrl = ({ id }: PutAdminResourcesIdPathParameters,) => {


  

  return `/admin/resources/${id}`
}

export const putAdminResourcesId = async ({ id }: PutAdminResourcesIdPathParameters,
    adminResourceUpsertRequest: AdminResourceUpsertRequest, options?: RequestInit): Promise<putAdminResourcesIdResponse> => {
  
  return customFetch<putAdminResourcesIdResponse>(getPutAdminResourcesIdUrl({ id }),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminResourceUpsertRequest,)
  }
);}


export type deleteAdminResourcesIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteAdminResourcesIdResponseSuccess = (deleteAdminResourcesIdResponse200) & {
  headers: Headers;
};
;

export type deleteAdminResourcesIdResponse = (deleteAdminResourcesIdResponseSuccess)

export const getDeleteAdminResourcesIdUrl = ({ id }: DeleteAdminResourcesIdPathParameters,) => {


  

  return `/admin/resources/${id}`
}

export const deleteAdminResourcesId = async ({ id }: DeleteAdminResourcesIdPathParameters, options?: RequestInit): Promise<deleteAdminResourcesIdResponse> => {
  
  return customFetch<deleteAdminResourcesIdResponse>(getDeleteAdminResourcesIdUrl({ id }),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type patchAdminResourcesIdReviewResponse200 = {
  data: void
  status: 200
}
    
export type patchAdminResourcesIdReviewResponseSuccess = (patchAdminResourcesIdReviewResponse200) & {
  headers: Headers;
};
;

export type patchAdminResourcesIdReviewResponse = (patchAdminResourcesIdReviewResponseSuccess)

export const getPatchAdminResourcesIdReviewUrl = ({ id }: PatchAdminResourcesIdReviewPathParameters,) => {


  

  return `/admin/resources/${id}/review`
}

export const patchAdminResourcesIdReview = async ({ id }: PatchAdminResourcesIdReviewPathParameters,
    adminResourceReviewRequest: AdminResourceReviewRequest, options?: RequestInit): Promise<patchAdminResourcesIdReviewResponse> => {
  
  return customFetch<patchAdminResourcesIdReviewResponse>(getPatchAdminResourcesIdReviewUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminResourceReviewRequest,)
  }
);}


export type postAdminResourcesIdRejectResponse200 = {
  data: void
  status: 200
}
    
export type postAdminResourcesIdRejectResponseSuccess = (postAdminResourcesIdRejectResponse200) & {
  headers: Headers;
};
;

export type postAdminResourcesIdRejectResponse = (postAdminResourcesIdRejectResponseSuccess)

export const getPostAdminResourcesIdRejectUrl = ({ id }: PostAdminResourcesIdRejectPathParameters,) => {


  

  return `/admin/resources/${id}/reject`
}

export const postAdminResourcesIdReject = async ({ id }: PostAdminResourcesIdRejectPathParameters, options?: RequestInit): Promise<postAdminResourcesIdRejectResponse> => {
  
  return customFetch<postAdminResourcesIdRejectResponse>(getPostAdminResourcesIdRejectUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


