/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type {
  CreateAssessmentPathRequest,
  DeleteJdSubmissionsJdIdAssessmentPathPathParameters,
  PostJdSubmissionsJdIdAssessmentPathPathParameters
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';

export type postJdSubmissionsJdIdAssessmentPathResponse200 = {
  data: void
  status: 200
}
    
export type postJdSubmissionsJdIdAssessmentPathResponseSuccess = (postJdSubmissionsJdIdAssessmentPathResponse200) & {
  headers: Headers;
};
;

export type postJdSubmissionsJdIdAssessmentPathResponse = (postJdSubmissionsJdIdAssessmentPathResponseSuccess)

export const getPostJdSubmissionsJdIdAssessmentPathUrl = ({ jdId }: PostJdSubmissionsJdIdAssessmentPathPathParameters,) => {


  

  return `/jd-submissions/${jdId}/assessment-path`
}

export const postJdSubmissionsJdIdAssessmentPath = async ({ jdId }: PostJdSubmissionsJdIdAssessmentPathPathParameters,
    createAssessmentPathRequest: CreateAssessmentPathRequest, options?: RequestInit): Promise<postJdSubmissionsJdIdAssessmentPathResponse> => {
  
  return customFetch<postJdSubmissionsJdIdAssessmentPathResponse>(getPostJdSubmissionsJdIdAssessmentPathUrl({ jdId }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAssessmentPathRequest,)
  }
);}


export type deleteJdSubmissionsJdIdAssessmentPathResponse200 = {
  data: void
  status: 200
}
    
export type deleteJdSubmissionsJdIdAssessmentPathResponseSuccess = (deleteJdSubmissionsJdIdAssessmentPathResponse200) & {
  headers: Headers;
};
;

export type deleteJdSubmissionsJdIdAssessmentPathResponse = (deleteJdSubmissionsJdIdAssessmentPathResponseSuccess)

export const getDeleteJdSubmissionsJdIdAssessmentPathUrl = ({ jdId }: DeleteJdSubmissionsJdIdAssessmentPathPathParameters,) => {


  

  return `/jd-submissions/${jdId}/assessment-path`
}

export const deleteJdSubmissionsJdIdAssessmentPath = async ({ jdId }: DeleteJdSubmissionsJdIdAssessmentPathPathParameters, options?: RequestInit): Promise<deleteJdSubmissionsJdIdAssessmentPathResponse> => {
  
  return customFetch<deleteJdSubmissionsJdIdAssessmentPathResponse>(getDeleteJdSubmissionsJdIdAssessmentPathUrl({ jdId }),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


