/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';



export const getGetAdminSubscriptionTiersMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/admin/subscription-tiers', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getPutAdminSubscriptionTiersTierCodeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/admin/subscription-tiers/:tierCode', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getAdminSubscriptionTiersMock = () => [
  getGetAdminSubscriptionTiersMockHandler(),
  getPutAdminSubscriptionTiersTierCodeMockHandler()
]
