export { DashboardPage } from './pages/dashboard-page'
export { AnalysisHistoryPage } from './pages/analysis-history-page'
export { LearningPathPage } from './pages/learning-path-page'
export { MarketPage } from './pages/market-page'
export { SettingsPage } from './pages/settings-page'
export { CertificatesPage } from './pages/certificates-page'
export { SkillsCvPage } from './pages/skills-cv-page'
