/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

export const getPostAssessmentPathsPathIdSessionsMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/assessment-paths/:pathId/sessions',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetAssessmentSessionsSessionIdQuestionsMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/assessment-sessions/:sessionId/questions',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getPostAssessmentSessionsSessionIdSubmitMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/assessment-sessions/:sessionId/submit',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetAssessmentSessionsSessionIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/assessment-sessions/:sessionId',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetJdSubmissionsJdIdReusableSessionsMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/jd-submissions/:jdId/reusable-sessions',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}
export const getAssessmentSessionsMock = () => [
  getPostAssessmentPathsPathIdSessionsMockHandler(),
  getGetAssessmentSessionsSessionIdQuestionsMockHandler(),
  getPostAssessmentSessionsSessionIdSubmitMockHandler(),
  getGetAssessmentSessionsSessionIdMockHandler(),
  getGetJdSubmissionsJdIdReusableSessionsMockHandler()
]
