/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

export const getPostJdSubmissionsMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/jd-submissions',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetJdSubmissionsMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/jd-submissions',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetJdSubmissionsIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/jd-submissions/:id',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getDeleteJdSubmissionsIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.delete(
    '*/jd-submissions/:id',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}
export const getJdSubmissionsMock = () => [
  getPostJdSubmissionsMockHandler(),
  getGetJdSubmissionsMockHandler(),
  getGetJdSubmissionsIdMockHandler(),
  getDeleteJdSubmissionsIdMockHandler()
]
