/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface AddCertificateRequest {
  /** @nullable */
  name?: string | null
  /** @nullable */
  issuer?: string | null
  /** @nullable */
  issuedDate?: string | null
  /** @nullable */
  expiresDate?: string | null
  /** @nullable */
  credentialUrl?: string | null
  /** @nullable */
  fileUrl?: string | null
  isVisible?: boolean
}
