/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface AddProjectRequest {
  /** @nullable */
  title?: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  repoUrl?: string | null
  /** @nullable */
  liveUrl?: string | null
  /** @nullable */
  imageUrl?: string | null
  /** @nullable */
  techStack?: string[] | null
  /** @nullable */
  role?: string | null
  /** @nullable */
  startedDate?: string | null
  /** @nullable */
  completedDate?: string | null
  isVisible?: boolean
}
