/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type { AdminSkillMappingDto } from './adminSkillMappingDto';

export interface AdminResourceUpsertRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  provider?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  description?: string | null;
  isFree?: boolean;
  /** @nullable */
  accessType?: string | null;
  /** @nullable */
  affiliateLabel?: string | null;
  /** @nullable */
  affiliateCommissionRate?: number | null;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  durationMinutes?: number | null;
  /** @nullable */
  needsAdminReview?: boolean | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  skillMappings?: AdminSkillMappingDto[] | null;
}
