/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface ApproveSkillRequest {
  /** @nullable */
  name?: string | null
  /** @nullable */
  category?: string | null
  /** @nullable */
  major?: string | null
  /** @nullable */
  difficultyLevel?: number | null
  /** @nullable */
  description?: string | null
}
