/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface CreateSkillRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  major?: string | null;
  /** @nullable */
  description?: string | null;
  difficultyLevel?: number;
}
