/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export type GetAdminResourcesParams = {
  type?: string
  search?: string
  needsReview?: boolean
  isActive?: boolean
  page?: number
  pageSize?: number
}
