/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export type GetAdminSkillsParams = {
search?: string;
major?: string;
category?: string;
isActive?: boolean;
page?: number;
pageSize?: number;
};
