/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export type GetAdminPaymentOrdersParams = {
status?: string;
provider?: string;
fromDate?: string;
toDate?: string;
search?: string;
page?: number;
pageSize?: number;
};
