/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export type PostAdminRagDocumentsBody = {
  file?: Blob
  title?: string
  sourceType?: string
  relatedSkillIds?: string[]
}
