/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface SepayWebhookPayload {
  id?: number;
  /** @nullable */
  gateway?: string | null;
  /** @nullable */
  transactionDate?: string | null;
  /** @nullable */
  accountNumber?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  content?: string | null;
  transferType?: number;
  transferAmount?: number;
  accumulated?: number;
  /** @nullable */
  referenceCode?: string | null;
  /** @nullable */
  description?: string | null;
}
