/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface SubmitOnboardingRequest {
  /** @nullable */
  academicYear?: string | null;
  /** @nullable */
  major?: string | null;
  /** @nullable */
  primaryGoal?: string | null;
  /** @nullable */
  weeklyStudyHours?: string | null;
  /** @nullable */
  proficiencyLevel?: string | null;
  /** @nullable */
  learningPriority?: string | null;
  /** @nullable */
  learningBudget?: string | null;
  /** @nullable */
  preferredChannel?: string | null;
}
