/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type { SubmitAnswerDto } from './submitAnswerDto';

export interface SubmitAssessmentSessionRequest {
  /** @nullable */
  answers?: SubmitAnswerDto[] | null;
}
