/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface TokenRefreshRequest {
  /** @nullable */
  refreshToken?: string | null
}
