/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface UpdateSubscriptionTierRequest {
  /** @nullable */
  priceMonthly?: number | null;
  /** @nullable */
  jdQuota?: number | null;
  /** @nullable */
  gapAnalysisQuota?: number | null;
  /** @nullable */
  assessmentQuota?: number | null;
  /** @nullable */
  roadmapActiveQuota?: number | null;
  /** @nullable */
  careerTrackQuota?: number | null;
  /** @nullable */
  portfolioCertificateQuota?: number | null;
  /** @nullable */
  portfolioProjectQuota?: number | null;
  /** @nullable */
  fullGapHistory?: boolean | null;
  /** @nullable */
  isActive?: boolean | null;
}
