/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */

export interface UpdatePortfolioRequest {
  /** @nullable */
  headline?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  coverImageUrl?: string | null;
  showCompletedSkills?: boolean;
  showCertificates?: boolean;
  showProjects?: boolean;
  isPublic?: boolean;
}
