/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type {
  UpdateCurrentUserRequest
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';

export type getUsersMeResponse200 = {
  data: void
  status: 200
}
    
export type getUsersMeResponseSuccess = (getUsersMeResponse200) & {
  headers: Headers;
};
;

export type getUsersMeResponse = (getUsersMeResponseSuccess)

export const getGetUsersMeUrl = () => {


  

  return `/users/me`
}

export const getUsersMe = async ( options?: RequestInit): Promise<getUsersMeResponse> => {
  
  return customFetch<getUsersMeResponse>(getGetUsersMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type putUsersMeResponse200 = {
  data: void
  status: 200
}
    
export type putUsersMeResponseSuccess = (putUsersMeResponse200) & {
  headers: Headers;
};
;

export type putUsersMeResponse = (putUsersMeResponseSuccess)

export const getPutUsersMeUrl = () => {


  

  return `/users/me`
}

export const putUsersMe = async (updateCurrentUserRequest: UpdateCurrentUserRequest, options?: RequestInit): Promise<putUsersMeResponse> => {
  
  return customFetch<putUsersMeResponse>(getPutUsersMeUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCurrentUserRequest,)
  }
);}


