/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

export const getPostCareerTracksMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/career-tracks',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetCareerTracksMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/career-tracks',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getGetCareerTracksIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/career-tracks/:id',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getPutCareerTracksIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.put(
    '*/career-tracks/:id',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getDeleteCareerTracksIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.delete(
    '*/career-tracks/:id',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getPostCareerTracksIdJdsMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/career-tracks/:id/jds',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}

export const getDeleteCareerTracksIdJdsJdIdMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions
) => {
  return http.delete(
    '*/career-tracks/:id/jds/:jdId',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 200 })
    },
    options
  )
}
export const getCareerTracksMock = () => [
  getPostCareerTracksMockHandler(),
  getGetCareerTracksMockHandler(),
  getGetCareerTracksIdMockHandler(),
  getPutCareerTracksIdMockHandler(),
  getDeleteCareerTracksIdMockHandler(),
  getPostCareerTracksIdJdsMockHandler(),
  getDeleteCareerTracksIdJdsJdIdMockHandler()
]
