/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type {
  AddJdToCareerTrackCommand,
  CreateCareerTrackCommand,
  DeleteCareerTracksIdJdsJdIdPathParameters,
  DeleteCareerTracksIdPathParameters,
  GetCareerTracksIdPathParameters,
  PostCareerTracksIdJdsPathParameters,
  PutCareerTracksIdPathParameters,
  UpdateCareerTrackCommand
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';

export type postCareerTracksResponse200 = {
  data: void
  status: 200
}
    
export type postCareerTracksResponseSuccess = (postCareerTracksResponse200) & {
  headers: Headers;
};
;

export type postCareerTracksResponse = (postCareerTracksResponseSuccess)

export const getPostCareerTracksUrl = () => {


  

  return `/career-tracks`
}

export const postCareerTracks = async (createCareerTrackCommand: CreateCareerTrackCommand, options?: RequestInit): Promise<postCareerTracksResponse> => {
  
  return customFetch<postCareerTracksResponse>(getPostCareerTracksUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCareerTrackCommand,)
  }
);}


export type getCareerTracksResponse200 = {
  data: void
  status: 200
}
    
export type getCareerTracksResponseSuccess = (getCareerTracksResponse200) & {
  headers: Headers;
};
;

export type getCareerTracksResponse = (getCareerTracksResponseSuccess)

export const getGetCareerTracksUrl = () => {


  

  return `/career-tracks`
}

export const getCareerTracks = async ( options?: RequestInit): Promise<getCareerTracksResponse> => {
  
  return customFetch<getCareerTracksResponse>(getGetCareerTracksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getCareerTracksIdResponse200 = {
  data: void
  status: 200
}
    
export type getCareerTracksIdResponseSuccess = (getCareerTracksIdResponse200) & {
  headers: Headers;
};
;

export type getCareerTracksIdResponse = (getCareerTracksIdResponseSuccess)

export const getGetCareerTracksIdUrl = ({ id }: GetCareerTracksIdPathParameters,) => {


  

  return `/career-tracks/${id}`
}

export const getCareerTracksId = async ({ id }: GetCareerTracksIdPathParameters, options?: RequestInit): Promise<getCareerTracksIdResponse> => {
  
  return customFetch<getCareerTracksIdResponse>(getGetCareerTracksIdUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type putCareerTracksIdResponse200 = {
  data: void
  status: 200
}
    
export type putCareerTracksIdResponseSuccess = (putCareerTracksIdResponse200) & {
  headers: Headers;
};
;

export type putCareerTracksIdResponse = (putCareerTracksIdResponseSuccess)

export const getPutCareerTracksIdUrl = ({ id }: PutCareerTracksIdPathParameters,) => {


  

  return `/career-tracks/${id}`
}

export const putCareerTracksId = async ({ id }: PutCareerTracksIdPathParameters,
    updateCareerTrackCommand: UpdateCareerTrackCommand, options?: RequestInit): Promise<putCareerTracksIdResponse> => {
  
  return customFetch<putCareerTracksIdResponse>(getPutCareerTracksIdUrl({ id }),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCareerTrackCommand,)
  }
);}


export type deleteCareerTracksIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteCareerTracksIdResponseSuccess = (deleteCareerTracksIdResponse200) & {
  headers: Headers;
};
;

export type deleteCareerTracksIdResponse = (deleteCareerTracksIdResponseSuccess)

export const getDeleteCareerTracksIdUrl = ({ id }: DeleteCareerTracksIdPathParameters,) => {


  

  return `/career-tracks/${id}`
}

export const deleteCareerTracksId = async ({ id }: DeleteCareerTracksIdPathParameters, options?: RequestInit): Promise<deleteCareerTracksIdResponse> => {
  
  return customFetch<deleteCareerTracksIdResponse>(getDeleteCareerTracksIdUrl({ id }),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type postCareerTracksIdJdsResponse200 = {
  data: void
  status: 200
}
    
export type postCareerTracksIdJdsResponseSuccess = (postCareerTracksIdJdsResponse200) & {
  headers: Headers;
};
;

export type postCareerTracksIdJdsResponse = (postCareerTracksIdJdsResponseSuccess)

export const getPostCareerTracksIdJdsUrl = ({ id }: PostCareerTracksIdJdsPathParameters,) => {


  

  return `/career-tracks/${id}/jds`
}

export const postCareerTracksIdJds = async ({ id }: PostCareerTracksIdJdsPathParameters,
    addJdToCareerTrackCommand: AddJdToCareerTrackCommand, options?: RequestInit): Promise<postCareerTracksIdJdsResponse> => {
  
  return customFetch<postCareerTracksIdJdsResponse>(getPostCareerTracksIdJdsUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addJdToCareerTrackCommand,)
  }
);}


export type deleteCareerTracksIdJdsJdIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteCareerTracksIdJdsJdIdResponseSuccess = (deleteCareerTracksIdJdsJdIdResponse200) & {
  headers: Headers;
};
;

export type deleteCareerTracksIdJdsJdIdResponse = (deleteCareerTracksIdJdsJdIdResponseSuccess)

export const getDeleteCareerTracksIdJdsJdIdUrl = ({ id, jdId }: DeleteCareerTracksIdJdsJdIdPathParameters,) => {


  

  return `/career-tracks/${id}/jds/${jdId}`
}

export const deleteCareerTracksIdJdsJdId = async ({ id, jdId }: DeleteCareerTracksIdJdsJdIdPathParameters, options?: RequestInit): Promise<deleteCareerTracksIdJdsJdIdResponse> => {
  
  return customFetch<deleteCareerTracksIdJdsJdIdResponse>(getDeleteCareerTracksIdJdsJdIdUrl({ id, jdId }),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


