/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type {
  GoogleLoginRequest,
  LoginRequest,
  LogoutRequest,
  RegisterRequest,
  TokenRefreshRequest
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';

export type postAuthRegisterResponse200 = {
  data: void
  status: 200
}
    
export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse200) & {
  headers: Headers;
};
;

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess)

export const getPostAuthRegisterUrl = () => {


  

  return `/auth/register`
}

export const postAuthRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<postAuthRegisterResponse> => {
  
  return customFetch<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}


export type postAuthLoginResponse200 = {
  data: void
  status: 200
}
    
export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
;

export type postAuthLoginResponse = (postAuthLoginResponseSuccess)

export const getPostAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const postAuthLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<postAuthLoginResponse> => {
  
  return customFetch<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}


export type postAuthGoogleResponse200 = {
  data: void
  status: 200
}
    
export type postAuthGoogleResponseSuccess = (postAuthGoogleResponse200) & {
  headers: Headers;
};
;

export type postAuthGoogleResponse = (postAuthGoogleResponseSuccess)

export const getPostAuthGoogleUrl = () => {


  

  return `/auth/google`
}

export const postAuthGoogle = async (googleLoginRequest: GoogleLoginRequest, options?: RequestInit): Promise<postAuthGoogleResponse> => {
  
  return customFetch<postAuthGoogleResponse>(getPostAuthGoogleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      googleLoginRequest,)
  }
);}


export type postAuthRefreshResponse200 = {
  data: void
  status: 200
}
    
export type postAuthRefreshResponseSuccess = (postAuthRefreshResponse200) & {
  headers: Headers;
};
;

export type postAuthRefreshResponse = (postAuthRefreshResponseSuccess)

export const getPostAuthRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const postAuthRefresh = async (tokenRefreshRequest: TokenRefreshRequest, options?: RequestInit): Promise<postAuthRefreshResponse> => {
  
  return customFetch<postAuthRefreshResponse>(getPostAuthRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenRefreshRequest,)
  }
);}


export type postAuthLogoutResponse200 = {
  data: void
  status: 200
}
    
export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess)

export const getPostAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const postAuthLogout = async (logoutRequest: LogoutRequest, options?: RequestInit): Promise<postAuthLogoutResponse> => {
  
  return customFetch<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logoutRequest,)
  }
);}


