/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Edu-Nexus API
 * OpenAPI spec version: v1
 */
import type { CreateOrderRequest, GetSubscriptionOrdersParams, SepayWebhookPayload } from '../../model'

import { customFetch } from '../../mutator/custom-fetch'

export type getSubscriptionTiersResponse200 = {
  data: void
  status: 200
}

export type getSubscriptionTiersResponseSuccess = getSubscriptionTiersResponse200 & {
  headers: Headers
}
export type getSubscriptionTiersResponse = getSubscriptionTiersResponseSuccess

export const getGetSubscriptionTiersUrl = () => {
  return `/subscription/tiers`
}

export const getSubscriptionTiers = async (options?: RequestInit): Promise<getSubscriptionTiersResponse> => {
  return customFetch<getSubscriptionTiersResponse>(getGetSubscriptionTiersUrl(), {
    ...options,
    method: 'GET'
  })
}

export type getSubscriptionMeResponse200 = {
  data: void
  status: 200
}

export type getSubscriptionMeResponseSuccess = getSubscriptionMeResponse200 & {
  headers: Headers
}
export type getSubscriptionMeResponse = getSubscriptionMeResponseSuccess

export const getGetSubscriptionMeUrl = () => {
  return `/subscription/me`
}

export const getSubscriptionMe = async (options?: RequestInit): Promise<getSubscriptionMeResponse> => {
  return customFetch<getSubscriptionMeResponse>(getGetSubscriptionMeUrl(), {
    ...options,
    method: 'GET'
  })
}

export type getSubscriptionOrdersResponse200 = {
  data: void
  status: 200
}

export type getSubscriptionOrdersResponseSuccess = getSubscriptionOrdersResponse200 & {
  headers: Headers
}
export type getSubscriptionOrdersResponse = getSubscriptionOrdersResponseSuccess

export const getGetSubscriptionOrdersUrl = (params?: GetSubscriptionOrdersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/subscription/orders?${stringifiedParams}` : `/subscription/orders`
}

export const getSubscriptionOrders = async (
  params?: GetSubscriptionOrdersParams,
  options?: RequestInit
): Promise<getSubscriptionOrdersResponse> => {
  return customFetch<getSubscriptionOrdersResponse>(getGetSubscriptionOrdersUrl(params), {
    ...options,
    method: 'GET'
  })
}

export type postSubscriptionOrdersResponse200 = {
  data: void
  status: 200
}

export type postSubscriptionOrdersResponseSuccess = postSubscriptionOrdersResponse200 & {
  headers: Headers
}
export type postSubscriptionOrdersResponse = postSubscriptionOrdersResponseSuccess

export const getPostSubscriptionOrdersUrl = () => {
  return `/subscription/orders`
}

export const postSubscriptionOrders = async (
  createOrderRequest: CreateOrderRequest,
  options?: RequestInit
): Promise<postSubscriptionOrdersResponse> => {
  return customFetch<postSubscriptionOrdersResponse>(getPostSubscriptionOrdersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrderRequest)
  })
}

export type postSubscriptionWebhookResponse200 = {
  data: void
  status: 200
}

export type postSubscriptionWebhookResponseSuccess = postSubscriptionWebhookResponse200 & {
  headers: Headers
}
export type postSubscriptionWebhookResponse = postSubscriptionWebhookResponseSuccess

export const getPostSubscriptionWebhookUrl = () => {
  return `/subscription/webhook`
}

export const postSubscriptionWebhook = async (
  sepayWebhookPayload: SepayWebhookPayload,
  options?: RequestInit
): Promise<postSubscriptionWebhookResponse> => {
  return customFetch<postSubscriptionWebhookResponse>(getPostSubscriptionWebhookUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sepayWebhookPayload)
  })
}
